---
# tasks file for zk-compose
- name: install python-pip
  yum:
   name: "{{ item }}"
  loop:
    - python-pip

- name: install docker-compose
  pip:
    name: "{{ item }}"
  loop:
    - docker-compose

- name: create directory
  file:
    path: "{{ item.path }}"
    state: directory
    mode: 0755
    recurse: yes
  loop: "{{ directorys }}"

- name: generate docker-compose  
  template:
    src: docker-compose.yaml.j2
    dest: "{{ docker_compose_path }}/docker-compose.yaml"
    mode: 0755
- name: docker-compose up -d
  shell: |
    docker-compose up -d
  args:
    chdir: "{{ docker_compose_path }}"

    
