---
# tasks file for jdk
- name: copy jdk
  unarchive:
    src: "{{ repo_address }}/jdk/{{ jdk_version }}/jdk.tar.gz"
    dest: /usr/local/
    remote_src: yes
  become: true
- name: create jdk directory link
  file:
    src: /usr/local/jdk{{ jdk_version }}
    dest: /usr/local/jdk
    state: link
  become: true
- name: add env to profile
  blockinfile:
    path: /etc/profile
    block: |
      export JAVA_HOME=/usr/local/jdk
      export CLASSPATH=.$CLASSPATH:$JAVA_HOME/lib/tools.jar:$JAVA_HOME/lib/dt.jar:,
      export PATH=$PATH:$JAVA_HOME/bin
      export JRE_HOME=$JAVA_HOME/jre
    marker: "# {mark} ANSIBLE MANAGED BLOCK jdk profile"
  become: true
- name: source profile
  shell: source /etc/profile
