---
# tasks file for docker
- name: Add repository
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    mode: 0644

- name: yum install
  yum:
    name: '{{ packages }}'
    state: latest
  vars:
    packages: "{{ pkgs }}"

- name: 创建docker 数据目录
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  loop:
    - "{{ docker-data-path }}"
    - /etc/docker

- name:  修改 docker 路径
  lineinfile:
    path: /lib/systemd/system/docker.service
    regexp: '^ExecStart='
    line: 'ExecStart=/usr/bin/dockerd --data-root={{ docker-data-path }}'

- name: 修改daemon.json
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json


- name: force systemd to reread configs
  systemd:
    daemon_reload: yes

- name: 启动docker
  systemd:
    name: docker
    state: started
