---
# vars file for docker
directorys:
  - name: docker-data-path
    value: /data/docker-data
  - name: docker-daemon-path
    value: /etc/docker

pkgs:
  - yum-utils
  - device-mapper-persistent-data
  - lvm2
  - docker-ce
