---
- name: create ssl directory
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    recurse: yes
  loop:
    - "{{ gen_ssl_path }}"
    - /data/packages
    - "{{ project_bin_path }}"
    - "{{ project_config_path }}/ssl"
    - "{{ project_config_path }}/cfg"
