---
- import_tasks: common.yml
  tags:
    - etcd
    - zrq-etcd
- name: create ssl directory
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    recurse: yes
  loop:
    - "{{etcd_cluster_data_dir}}"
  tags:
    - etcd
    - zrq-etcd

- name: copy server.pem server-key.pem ca.pem ca-key.pem to etcd nodes  
  copy:
    src: ssl/{{item}}
    dest: /data/kubernetes/ssl/{{item}}
    mode: 0755
  loop:
    - server.pem
    - server-key.pem
    - ca.pem
    - ca-key.pem
  tags:
    - etcd
    - zrq-etcd

- name: copy etcd config
  template:
    src: etcd.j2
    dest: /data/kubernetes/cfg/etcd 
    mode: 0644
    #when: etcd_list[inventory_hostname] | default ('False') in etcd_list.values() | list
  tags:
    - etcd
    - zrq-j2

- name: copy etcd service 
  copy:
    src: etcd.service
    dest: /usr/lib/systemd/system/etcd.service
    mode: 0755
    #when: etcd_list[inventory_hostname] | default ('False') in etcd_list.values() | list
  tags:
    - etcd

- name: just force systemd to reread configs (2.4 and above)
  systemd: daemon_reload=yes
  tags:
    - etcd

- name: copy etcd
  get_url:
    url: "{{ repo_address }}/etcd/{{ etcd_version }}/{{ item.name }}"
    dest: /data/kubernetes/bin/{{ item.value }}
    mode: 0755
    timeout: 150
  loop:
    - { name: 'etcd', value: 'etcd' }
    - { name: 'etcdctl', value: 'etcdctl' }
      # when: etcd_list[inventory_hostname] | default ('False') in etcd_list.values() | list 
  tags: 
    - etcd-config
    - etcd
    - zrq-etcd-copy

- name: start etcd
  systemd:
    name: etcd
    state: started
    daemon_reload: yes
  tags: 
    - start-etcd
    - etcd

- name: add /data/kubernetes/bin to PATH
  blockinfile:
    path: /etc/profile
    block: |
      export PATH=/data/kubernetes/bin:$PATH
    marker: "# {mark} ANSIBLE MANAGED BLOCK ADD K8S AND ETCD  ENV"
  become: true  
  tags:
    - addenv
    - etcd
- name: 添加 etcdctl 别名
  blockinfile: 
    path: /root/.bashrc
    block: | 
      alias etcdctl='etcdctl --ca-file=/data/kubernetes/ssl/ca.pem --key-file=/data/kubernetes/ssl/server-key.pem --cert-file=/data/kubernetes/ssl/server.pem'
    marker: "#add etcdctl to bashrc"
  tags:
    - etcd
  

- name: copy add network sh
  template:
    src: add_network_to_etcd.j2
    dest: /data/kubernetes/bin/add_network_to_etcd.sh
    mode: 0755
  tags:
    - etcd

- name: create network in etcd
  shell: /bin/bash add_network_to_etcd.sh
  args:
    chdir: /data/kubernetes/bin
    executable: /bin/bash 
  run_once: true
  tags:
    - etcd 


 
