---
# tasks file for zabbix
- name: 拷贝redis安装包并解压
  unarchive:
    src: "{{ repo_address }}/{{ item.name }}/{{ item.version }}/{{ item.pkg}}"
    dest: /data/packages
    remote_src: yes
  loop:
    - {'name': zabbix, 'version': '{{ zabbix_version }}', 'pkg': zabbix.tar.gz }

- name: 创建zabbix 用户
  user:
    name: zabbix
    createhome: no

- name: 编译 
  shell: "{{ item }}"
  args:
    chdir: "/data/packages/zabbix-{{ zabbix_version }}"
  loop:
    - ./configure --prefix=/usr/local/zabbix-3.2.0 --sysconfdir=/etc/zabbix_agentd --enable-agent
    - make
    - make install 



