---
# tasks file for zookeeper
- name: create zookeeper dirs
  file: 
    path: "{{ zk_root_path }}/{{ item}}"
    state: directory
    mode: 0755
    recurse: yes
  loop:
    - data
    - logs

- name: 下载zookeeper
  unarchive:
    src: "{{ repo_address }}/zookeeper/{{ zk_version }}/zookeeper.tar.gz"
    dest: "{{ zk_root_path}}"
    remote_src: yes

- name: add env to profile
  blockinfile:
    path: /etc/profile
    block: |
      export ZOOKEEPER_HOME={{ zk_root_path }}/zookeeper-{{ zk_version}}
      export PATH=$ZOOKEEPER_HOME/bin:$PATH
    marker: "# {mark} ANSIBLE MANAGED BLOCK zookeeper profile"
  become: true
- name: source profile
  shell: source /etc/profile

- name: copy config file
  template:
    src: zoo.cfg.j2
    dest: "{{ zk_root_path }}/zookeeper-{{ zk_version}}/conf/zoo.cfg"
    mode: 0644

- name: copy myid
  template:
    src: myid.j2
    dest: "{{ zk_root_path }}/data/myid"
    mode: 0644

- name: start zk
  shell: ./zkServer.sh start
  args:
    chdir: "{{ zk_root_path }}/zookeeper-{{ zk_version}}/bin/"

